/*
 * Copyright (C) 2018 Wild Swift
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package name.wildswift.mapache.generator.test

import org.gradle.testkit.runner.GradleRunner
import org.gradle.testkit.runner.TaskOutcome.SUCCESS
import org.junit.Assert.assertEquals
import org.junit.Before
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder
import java.io.File
import java.io.IOException
import java.io.OutputStreamWriter

/**
 * Created by swift
 */
class PluginTest {
    @get:Rule
    val testProjectDir = TemporaryFolder()

    private lateinit var localPropertiesFile: File

    @Before
    @Throws(IOException::class)
    fun setup() {
        localPropertiesFile = testProjectDir.newFile("local.properties")
    }

    @Test
    @Throws(IOException::class)
    fun testGenerationWithApplicationModule() {
        File("template").copyRecursively(testProjectDir.root)
        File("../local.properties").copyTo(localPropertiesFile, true)

        println(testProjectDir.root.absolutePath)

        val result = GradleRunner.create()
                .withProjectDir(testProjectDir.root)
                .withPluginClasspath()
                .withArguments("build", "--stacktrace")
                .forwardStdOutput(OutputStreamWriter(System.out))
                .forwardStdError(OutputStreamWriter(System.err))
                .build()

        assertEquals(SUCCESS, result.task(":app:build")?.outcome)

//        val attrRNames = appFolder.resolve("build/generated/source/resNames/release/name/wildswift/testapp/AttrRNames.java").readLines().joinToString("\n")
//        assertEquals("""
//            |// Generated by ws-android-resource-names gradle plugin. Do not modify!
//            |package name.wildswift.testapp;
//            |
//            |import java.lang.String;
//            |
//            |public final class AttrRNames {
//            |  public static final String textIn = "textIn";
//            |
//            |  public static final String visibleColor = "visibleColor";
//            |}
//        """.trimMargin(), attrRNames)
    }

}